language: node_js
node_js:
- '4.2'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  api_key:
    secure: kMfjk1qOwdJO0miyMVuAbHTTDtsfxdns2RhcE8QTBClHIJ/fgJVwys50MBS+yzAzhtAQ0NwcRsfkXhzXSNlKPBGuutxPyIU6JPqchEIyMntuu1vfa/tLY2L+k1lGhNgr+TFVSYl+BxZaLYGu9WIuvlg0tR5/8S3MTQHr50BgB8c=
  on:
    tags: true
