language: node_js
node_js:
- node
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install --quiet
script:
- jshint . -e .json
- npm test
deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: G5YVIuoGKRVINa9TQmGxIIcMtqG3FueeY2gqGoYie4nhiYUFZKTChOaWRWo7k1eRuOSnBy/Q+xHYOAdpG7y6ckMjxjLnIAdWt3STHkE8gBvOSkqNd758z4j14gExijXT32nYIcr2HqJJ76IsN9UEIheC8EIAj2xTQPGXBaHGMSA=
  on:
    tags: true
