language: node_js
sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '6.11'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install

script:
  - yarn test
  - yarn run eslint
  - yarn run jshint

deploy:
  provider: npm
  email: elmerbulthuis@gmail.com
  api_key:
    secure: gRSj8pgTUFXu7m78H3fMupNV1QGo22Z1CEpPCNX0+GCAjKAtgkv7EyE8kkd8eTctUoxBoAuk0QZdbi3aE8mqX4ozqaYKq+rB1d/9JQw/RrQY00qUQ8rTYFbtkJsWvd4qHQJpSCGWauxg/LwUXg/zcqVIyDu8ysPpiTW1Ebb9VIo=
  on:
    tags: true
    repo: LuvDaSun/angular-hal
